(fn render (obj &key (x 0))
  (update-canvas)
  (clear-canvas *ctx*)
  (render-object3d obj x 0 0 0 0 200)
  (do-wait 10 (render obj :x (++ x))))

(fn make-plane ()
  (with (vtl  (new vertex -80 -50 0)
         vtr  (new vertex 80 -50 0)
         vbl  (new vertex -80 50 0)
         vbr  (new vertex 80 50 0)
         f    (make-face :vertices (list vtl vtr vbr vbl)
                         :renderer [draw-face-filled *ctx* _ "#00f"]))
    (make-object3d :vertices (list vtl vtr vbl vbr)
                   :faces    (list f))))

(fn start-site ()
  (document-extend)
  (= document.body.style.margin 0)
  (disable-scrollbars)
  (= *texture* (make-video :width 640 :height 480 :webm "video.mp4" :loop? t :autoplay? t))
  (document.body.add *texture*)
  (*texture*.hide)
  (= *texture*.muted t)
  (!= (make-plane) ;(make-object3d-from-vertices-and-faces *vertices* *faces*)
    (native-add-event-listener *texture* "play" #'(() (render !)))))

(add-onload #'start-site)
