(fn render (obj)
  (update-canvas)
  (clear-canvas *ctx*)
  (render-object3d obj -45 0 0
                       0 0 200)
  (do-wait 10 (render obj)))

(fn make-plane ()
  (with (vtl  (make-vertex :ox -80 :oy -50 :oz 0)
         vtr  (make-vertex :ox 80 :oy -50 :oz 0)
         vbl  (make-vertex :ox -80 :oy 50 :oz 0)
         vbr  (make-vertex :ox 80 :oy 50 :oz 0)
         f    (make-face :vertices (list vtr vbr vbl) :renderer #'draw-face))
    (make-object3d :vertices (list vtl vtr vbl vbr)
                   :faces    (list f))))

(fn start-site ()
  (document-extend)
  (= document.body.style.margin 0)
  (disable-scrollbars)
  (= *texture* (make-video :width 640 :height 480 :webm "video.mp4" :loop? t :autoplay? t))
  (document.body.add *texture*)
  (*texture*.hide)
  (= *texture*.muted t)
  (!= (make-plane) ;(make-object3d-from-vertices-and-faces *vertices* *faces*)
    (native-add-event-listener *texture* "play" #'(() (render !)))))

(add-onload #'start-site)
